# Uncomment the next line to define a global platform for your project
# platform :ios, '13.1'

target 'DLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DLibrary
  pod 'ALCameraViewController'
  
  target 'DLibraryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DLibraryUITests' do
    # Pods for testing
  end

end
